services:
  gradinator-bot:
    build: .
    container_name: gradinator-bot
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    environment:
      TZ: Europe/Moscow
    volumes:
      - bot_data:/app/data

volumes:
  bot_data:
